### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by francwalter** [JakeSteam/ferdi-nextdoor#2]
Hi
In the [README.md](https://github.com/JakeSteam/ferdi-nextdoor#readme) there is a link to [Read the documentation](https://github.com/getferdi/recipes/blob/master/docs/integration.md) but this is a 404.
It is a dead link.
frank

**Comment by francwalter** [comment]
Should go to: [Overview / How to create a Ferdium integration](https://github.com/ferdium/ferdium-recipes/blob/main/docs/integration.md)

**Comment by JakeSteam** [comment]
Fixed @francwalter 

I knew Ferdi was having... issues, didn't realise it was completely gone though! Thanks,

**Comment by francwalter** [comment]
Which service do you use?
I just installed Ferdium to replace the good old but now too buggy Hamsket, but crucial features from Hamsket dont work: use own javascript on the services. The user.js does not touch the inner of the webview (in Hamsket, that worked).
EDIT: now it works, I had an error in my user.js (sorry)
